# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroArea',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='hero_area_heroarea', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('working_position', models.CharField(max_length=100)),
                ('background_image', models.ImageField(upload_to='hero_area/img/')),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('github_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('facebook_url', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
