# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroarea',
            name='background_image',
            field=models.ImageField(max_length=500, upload_to='hero_area/img/'),
        ),
    ]
