# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_area', '0003_auto_20180502_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortheroarea',
            old_name='working_position',
            new_name='favorite_quotes',
        ),
        migrations.AddField(
            model_name='shortheroarea',
            name='author',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
