# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('addons_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='addons_plugin_calendlyplugin', serialize=False, to='cms.CMSPlugin')),
                ('calendly_embedded_url', models.CharField(max_length=500)),
                ('message_text', models.CharField(max_length=250)),
                ('color', models.CharField(default='#76b51b', max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
