# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_plugin', '0002_calendlyplugin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendlyplugin',
            old_name='message_text',
            new_name='text_message',
        ),
    ]
