# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoUrlItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_url', models.CharField(max_length=500)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'IOS'), (2, 'Android'), (3, 'Web')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Image')], default=1)),
                ('media_asset', models.ImageField(default='', upload_to='portfolio/img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portfolio_app_project', serialize=False, to='cms.CMSPlugin')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=250, null=True)),
                ('short_description', models.TextField(default='')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='description')),
                ('skills', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('roles', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('length', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('demo_url', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('youtube_embed_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('top_image', models.ImageField(default='', max_length=500, upload_to='portfolio/img/top_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portfolio_app_tag', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='project', to='portfolio_app.Tag', verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.Project'),
        ),
        migrations.AddField(
            model_name='demourlitem',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.Project'),
        ),
    ]
