# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project_test_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='test_placeholder',
        ),
    ]
