# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 05:04
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('portfolio_app', '0004_project_hero_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='hero_area',
        ),
        migrations.AddField(
            model_name='project',
            name='heading',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='project_heading', to='cms.Placeholder'),
        ),
    ]
