# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_auto_20180427_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon_image',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to='portfolio/img/icon_image/'),
        ),
    ]
