# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_project_icon_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='heading',
            new_name='use_case',
        ),
    ]
