# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('statistic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='about_me_statisticplugin', serialize=False, to='cms.CMSPlugin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='statisticitem',
            name='statistic_plugin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.StatisticPlugin'),
        ),
    ]
