# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_auto_20180423_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillitem',
            old_name='statistic_plugin_item',
            new_name='skill_plugin_item',
        ),
    ]
