# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('about_me', '0005_auto_20180423_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeplugin',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='timelineheader',
            name='id',
        ),
        migrations.AddField(
            model_name='timelineheader',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, default='2', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='about_me_timelineheader', serialize=False, to='cms.CMSPlugin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelineheader',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResumePlugin',
        ),
    ]
