# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0006_auto_20180423_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineblock',
            name='period_time',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
