# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0007_timelineblock_period_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineblock',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
